/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IPaymentRegistry } from "./IPaymentRegistry";
export type { ReputationRegistry } from "./ReputationRegistry";
