/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IPaymentRegistryInterface extends Interface {
  getFunction(
    nameOrSignature: "getPayment" | "isTransactionRecorded"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getPayment",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isTransactionRecorded",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "getPayment", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isTransactionRecorded",
    data: BytesLike
  ): Result;
}

export interface IPaymentRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): IPaymentRegistry;
  waitForDeployment(): Promise<this>;

  interface: IPaymentRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getPayment: TypedContractMethod<
    [paymentId: BytesLike],
    [
      [
        bigint,
        string,
        string,
        bigint,
        string,
        string,
        string,
        bigint,
        string,
        boolean,
        boolean
      ] & {
        agentId: bigint;
        payer: string;
        payee: string;
        amount: bigint;
        token: string;
        serviceDescription: string;
        taskId: string;
        timestamp: bigint;
        txHash: string;
        verified: boolean;
        refunded: boolean;
      }
    ],
    "view"
  >;

  isTransactionRecorded: TypedContractMethod<
    [txHash: BytesLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getPayment"
  ): TypedContractMethod<
    [paymentId: BytesLike],
    [
      [
        bigint,
        string,
        string,
        bigint,
        string,
        string,
        string,
        bigint,
        string,
        boolean,
        boolean
      ] & {
        agentId: bigint;
        payer: string;
        payee: string;
        amount: bigint;
        token: string;
        serviceDescription: string;
        taskId: string;
        timestamp: bigint;
        txHash: string;
        verified: boolean;
        refunded: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isTransactionRecorded"
  ): TypedContractMethod<[txHash: BytesLike], [boolean], "view">;

  filters: {};
}
