/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace ReputationRegistry {
  export type FeedbackStruct = {
    agentId: BigNumberish;
    reviewer: AddressLike;
    rating: BigNumberish;
    comment: string;
    paymentProof: BytesLike;
    timestamp: BigNumberish;
    verified: boolean;
  };

  export type FeedbackStructOutput = [
    agentId: bigint,
    reviewer: string,
    rating: bigint,
    comment: string,
    paymentProof: string,
    timestamp: bigint,
    verified: boolean
  ] & {
    agentId: bigint;
    reviewer: string;
    rating: bigint;
    comment: string;
    paymentProof: string;
    timestamp: bigint;
    verified: boolean;
  };
}

export interface ReputationRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "agentFeedbacks"
      | "agentScores"
      | "blacklistReviewer"
      | "blacklistedReviewers"
      | "getAgentFeedbacks"
      | "getAgentFeedbacksPaginated"
      | "getFeedbackCount"
      | "getReputationScore"
      | "getReputationTier"
      | "isPaymentProofUsed"
      | "owner"
      | "paymentRegistry"
      | "renounceOwnership"
      | "setPaymentRegistry"
      | "submitFeedback"
      | "transferOwnership"
      | "usedPaymentProofs"
      | "whitelistReviewer"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FeedbackSubmitted"
      | "FeedbackVerified"
      | "OwnershipTransferred"
      | "ReviewerBlacklisted"
      | "ReviewerWhitelisted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "agentFeedbacks",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "agentScores",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "blacklistReviewer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "blacklistedReviewers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgentFeedbacks",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgentFeedbacksPaginated",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getFeedbackCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getReputationScore",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getReputationTier",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isPaymentProofUsed",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "paymentRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setPaymentRegistry",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitFeedback",
    values: [BigNumberish, BigNumberish, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "usedPaymentProofs",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "whitelistReviewer",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "agentFeedbacks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "agentScores",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "blacklistReviewer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "blacklistedReviewers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAgentFeedbacks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAgentFeedbacksPaginated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFeedbackCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReputationScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReputationTier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isPaymentProofUsed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "paymentRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPaymentRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitFeedback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "usedPaymentProofs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "whitelistReviewer",
    data: BytesLike
  ): Result;
}

export namespace FeedbackSubmittedEvent {
  export type InputTuple = [
    agentId: BigNumberish,
    reviewer: AddressLike,
    rating: BigNumberish,
    paymentProof: BytesLike
  ];
  export type OutputTuple = [
    agentId: bigint,
    reviewer: string,
    rating: bigint,
    paymentProof: string
  ];
  export interface OutputObject {
    agentId: bigint;
    reviewer: string;
    rating: bigint;
    paymentProof: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeedbackVerifiedEvent {
  export type InputTuple = [agentId: BigNumberish, feedbackIndex: BigNumberish];
  export type OutputTuple = [agentId: bigint, feedbackIndex: bigint];
  export interface OutputObject {
    agentId: bigint;
    feedbackIndex: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReviewerBlacklistedEvent {
  export type InputTuple = [reviewer: AddressLike];
  export type OutputTuple = [reviewer: string];
  export interface OutputObject {
    reviewer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReviewerWhitelistedEvent {
  export type InputTuple = [reviewer: AddressLike];
  export type OutputTuple = [reviewer: string];
  export interface OutputObject {
    reviewer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ReputationRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ReputationRegistry;
  waitForDeployment(): Promise<this>;

  interface: ReputationRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  agentFeedbacks: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [bigint, string, bigint, string, string, bigint, boolean] & {
        agentId: bigint;
        reviewer: string;
        rating: bigint;
        comment: string;
        paymentProof: string;
        timestamp: bigint;
        verified: boolean;
      }
    ],
    "view"
  >;

  agentScores: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        totalRating: bigint;
        feedbackCount: bigint;
        averageRating: bigint;
      }
    ],
    "view"
  >;

  blacklistReviewer: TypedContractMethod<
    [reviewer: AddressLike],
    [void],
    "nonpayable"
  >;

  blacklistedReviewers: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  getAgentFeedbacks: TypedContractMethod<
    [agentId: BigNumberish],
    [ReputationRegistry.FeedbackStructOutput[]],
    "view"
  >;

  getAgentFeedbacksPaginated: TypedContractMethod<
    [agentId: BigNumberish, offset: BigNumberish, limit: BigNumberish],
    [ReputationRegistry.FeedbackStructOutput[]],
    "view"
  >;

  getFeedbackCount: TypedContractMethod<
    [agentId: BigNumberish],
    [bigint],
    "view"
  >;

  getReputationScore: TypedContractMethod<
    [agentId: BigNumberish],
    [[bigint, bigint] & { averageRating: bigint; feedbackCount: bigint }],
    "view"
  >;

  getReputationTier: TypedContractMethod<
    [agentId: BigNumberish],
    [bigint],
    "view"
  >;

  isPaymentProofUsed: TypedContractMethod<
    [paymentProof: BytesLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  paymentRegistry: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setPaymentRegistry: TypedContractMethod<
    [_paymentRegistry: AddressLike],
    [void],
    "nonpayable"
  >;

  submitFeedback: TypedContractMethod<
    [
      agentId: BigNumberish,
      rating: BigNumberish,
      comment: string,
      paymentProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  usedPaymentProofs: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  whitelistReviewer: TypedContractMethod<
    [reviewer: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "agentFeedbacks"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [bigint, string, bigint, string, string, bigint, boolean] & {
        agentId: bigint;
        reviewer: string;
        rating: bigint;
        comment: string;
        paymentProof: string;
        timestamp: bigint;
        verified: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "agentScores"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        totalRating: bigint;
        feedbackCount: bigint;
        averageRating: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "blacklistReviewer"
  ): TypedContractMethod<[reviewer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "blacklistedReviewers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "getAgentFeedbacks"
  ): TypedContractMethod<
    [agentId: BigNumberish],
    [ReputationRegistry.FeedbackStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAgentFeedbacksPaginated"
  ): TypedContractMethod<
    [agentId: BigNumberish, offset: BigNumberish, limit: BigNumberish],
    [ReputationRegistry.FeedbackStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getFeedbackCount"
  ): TypedContractMethod<[agentId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getReputationScore"
  ): TypedContractMethod<
    [agentId: BigNumberish],
    [[bigint, bigint] & { averageRating: bigint; feedbackCount: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getReputationTier"
  ): TypedContractMethod<[agentId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "isPaymentProofUsed"
  ): TypedContractMethod<[paymentProof: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "paymentRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPaymentRegistry"
  ): TypedContractMethod<[_paymentRegistry: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitFeedback"
  ): TypedContractMethod<
    [
      agentId: BigNumberish,
      rating: BigNumberish,
      comment: string,
      paymentProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usedPaymentProofs"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "whitelistReviewer"
  ): TypedContractMethod<[reviewer: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "FeedbackSubmitted"
  ): TypedContractEvent<
    FeedbackSubmittedEvent.InputTuple,
    FeedbackSubmittedEvent.OutputTuple,
    FeedbackSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "FeedbackVerified"
  ): TypedContractEvent<
    FeedbackVerifiedEvent.InputTuple,
    FeedbackVerifiedEvent.OutputTuple,
    FeedbackVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ReviewerBlacklisted"
  ): TypedContractEvent<
    ReviewerBlacklistedEvent.InputTuple,
    ReviewerBlacklistedEvent.OutputTuple,
    ReviewerBlacklistedEvent.OutputObject
  >;
  getEvent(
    key: "ReviewerWhitelisted"
  ): TypedContractEvent<
    ReviewerWhitelistedEvent.InputTuple,
    ReviewerWhitelistedEvent.OutputTuple,
    ReviewerWhitelistedEvent.OutputObject
  >;

  filters: {
    "FeedbackSubmitted(uint256,address,uint8,bytes32)": TypedContractEvent<
      FeedbackSubmittedEvent.InputTuple,
      FeedbackSubmittedEvent.OutputTuple,
      FeedbackSubmittedEvent.OutputObject
    >;
    FeedbackSubmitted: TypedContractEvent<
      FeedbackSubmittedEvent.InputTuple,
      FeedbackSubmittedEvent.OutputTuple,
      FeedbackSubmittedEvent.OutputObject
    >;

    "FeedbackVerified(uint256,uint256)": TypedContractEvent<
      FeedbackVerifiedEvent.InputTuple,
      FeedbackVerifiedEvent.OutputTuple,
      FeedbackVerifiedEvent.OutputObject
    >;
    FeedbackVerified: TypedContractEvent<
      FeedbackVerifiedEvent.InputTuple,
      FeedbackVerifiedEvent.OutputTuple,
      FeedbackVerifiedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ReviewerBlacklisted(address)": TypedContractEvent<
      ReviewerBlacklistedEvent.InputTuple,
      ReviewerBlacklistedEvent.OutputTuple,
      ReviewerBlacklistedEvent.OutputObject
    >;
    ReviewerBlacklisted: TypedContractEvent<
      ReviewerBlacklistedEvent.InputTuple,
      ReviewerBlacklistedEvent.OutputTuple,
      ReviewerBlacklistedEvent.OutputObject
    >;

    "ReviewerWhitelisted(address)": TypedContractEvent<
      ReviewerWhitelistedEvent.InputTuple,
      ReviewerWhitelistedEvent.OutputTuple,
      ReviewerWhitelistedEvent.OutputObject
    >;
    ReviewerWhitelisted: TypedContractEvent<
      ReviewerWhitelistedEvent.InputTuple,
      ReviewerWhitelistedEvent.OutputTuple,
      ReviewerWhitelistedEvent.OutputObject
    >;
  };
}
