/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as reputationRegistrySol from "./ReputationRegistry.sol";
export type { reputationRegistrySol };
export type { AgentIdentityRegistry } from "./AgentIdentityRegistry";
export type { PaymentRegistry } from "./PaymentRegistry";
export type { ValidationRegistry } from "./ValidationRegistry";
