/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AgentIdentityRegistry } from "./AgentIdentityRegistry";
export type { ReputationRegistry } from "./ReputationRegistry";
export type { ValidationRegistry } from "./ValidationRegistry";
