/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace PaymentRegistry {
  export type PaymentStruct = {
    agentId: BigNumberish;
    payer: AddressLike;
    payee: AddressLike;
    amount: BigNumberish;
    token: AddressLike;
    serviceDescription: string;
    taskId: string;
    timestamp: BigNumberish;
    txHash: BytesLike;
    verified: boolean;
    refunded: boolean;
  };

  export type PaymentStructOutput = [
    agentId: bigint,
    payer: string,
    payee: string,
    amount: bigint,
    token: string,
    serviceDescription: string,
    taskId: string,
    timestamp: bigint,
    txHash: string,
    verified: boolean,
    refunded: boolean
  ] & {
    agentId: bigint;
    payer: string;
    payee: string;
    amount: bigint;
    token: string;
    serviceDescription: string;
    taskId: string;
    timestamp: bigint;
    txHash: string;
    verified: boolean;
    refunded: boolean;
  };
}

export interface PaymentRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "agentEarnings"
      | "agentPayments"
      | "batchVerifyPayments"
      | "getAgentEarnings"
      | "getAgentPaymentStats"
      | "getAgentPayments"
      | "getGlobalStats"
      | "getPayerPayments"
      | "getPayment"
      | "getPaymentIdByTxHash"
      | "isTransactionRecorded"
      | "owner"
      | "payerPayments"
      | "payments"
      | "recordPayment"
      | "renounceOwnership"
      | "totalPayments"
      | "totalVolume"
      | "transferOwnership"
      | "txHashToPaymentId"
      | "verifyPayment"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "PaymentRecorded"
      | "PaymentRefunded"
      | "PaymentVerified"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "agentEarnings",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "agentPayments",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "batchVerifyPayments",
    values: [BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgentEarnings",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgentPaymentStats",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgentPayments",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getGlobalStats",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPayerPayments",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPayment",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPaymentIdByTxHash",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isTransactionRecorded",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "payerPayments",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "payments", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "recordPayment",
    values: [
      BigNumberish,
      AddressLike,
      BigNumberish,
      AddressLike,
      string,
      string,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalPayments",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalVolume",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "txHashToPaymentId",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyPayment",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "agentEarnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "agentPayments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchVerifyPayments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAgentEarnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAgentPaymentStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAgentPayments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGlobalStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPayerPayments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPayment", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPaymentIdByTxHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isTransactionRecorded",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "payerPayments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "payments", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalPayments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalVolume",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "txHashToPaymentId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyPayment",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentRecordedEvent {
  export type InputTuple = [
    paymentId: BytesLike,
    agentId: BigNumberish,
    payer: AddressLike,
    amount: BigNumberish,
    txHash: BytesLike
  ];
  export type OutputTuple = [
    paymentId: string,
    agentId: bigint,
    payer: string,
    amount: bigint,
    txHash: string
  ];
  export interface OutputObject {
    paymentId: string;
    agentId: bigint;
    payer: string;
    amount: bigint;
    txHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentRefundedEvent {
  export type InputTuple = [
    paymentId: BytesLike,
    agentId: BigNumberish,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    paymentId: string,
    agentId: bigint,
    amount: bigint
  ];
  export interface OutputObject {
    paymentId: string;
    agentId: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentVerifiedEvent {
  export type InputTuple = [paymentId: BytesLike, agentId: BigNumberish];
  export type OutputTuple = [paymentId: string, agentId: bigint];
  export interface OutputObject {
    paymentId: string;
    agentId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PaymentRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): PaymentRegistry;
  waitForDeployment(): Promise<this>;

  interface: PaymentRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  agentEarnings: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  agentPayments: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;

  batchVerifyPayments: TypedContractMethod<
    [paymentIds: BytesLike[]],
    [void],
    "nonpayable"
  >;

  getAgentEarnings: TypedContractMethod<
    [agentId: BigNumberish],
    [bigint],
    "view"
  >;

  getAgentPaymentStats: TypedContractMethod<
    [agentId: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        paymentCount: bigint;
        totalEarnings: bigint;
        verifiedCount: bigint;
      }
    ],
    "view"
  >;

  getAgentPayments: TypedContractMethod<
    [agentId: BigNumberish],
    [string[]],
    "view"
  >;

  getGlobalStats: TypedContractMethod<
    [],
    [
      [bigint, bigint] & {
        totalPaymentCount: bigint;
        totalPaymentVolume: bigint;
      }
    ],
    "view"
  >;

  getPayerPayments: TypedContractMethod<
    [payer: AddressLike],
    [string[]],
    "view"
  >;

  getPayment: TypedContractMethod<
    [paymentId: BytesLike],
    [PaymentRegistry.PaymentStructOutput],
    "view"
  >;

  getPaymentIdByTxHash: TypedContractMethod<
    [txHash: BytesLike],
    [string],
    "view"
  >;

  isTransactionRecorded: TypedContractMethod<
    [txHash: BytesLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  payerPayments: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  payments: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        bigint,
        string,
        string,
        bigint,
        string,
        string,
        string,
        bigint,
        string,
        boolean,
        boolean
      ] & {
        agentId: bigint;
        payer: string;
        payee: string;
        amount: bigint;
        token: string;
        serviceDescription: string;
        taskId: string;
        timestamp: bigint;
        txHash: string;
        verified: boolean;
        refunded: boolean;
      }
    ],
    "view"
  >;

  recordPayment: TypedContractMethod<
    [
      agentId: BigNumberish,
      payee: AddressLike,
      amount: BigNumberish,
      token: AddressLike,
      serviceDescription: string,
      taskId: string,
      txHash: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  totalPayments: TypedContractMethod<[], [bigint], "view">;

  totalVolume: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  txHashToPaymentId: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  verifyPayment: TypedContractMethod<
    [paymentId: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "agentEarnings"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "agentPayments"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "batchVerifyPayments"
  ): TypedContractMethod<[paymentIds: BytesLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAgentEarnings"
  ): TypedContractMethod<[agentId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAgentPaymentStats"
  ): TypedContractMethod<
    [agentId: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        paymentCount: bigint;
        totalEarnings: bigint;
        verifiedCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAgentPayments"
  ): TypedContractMethod<[agentId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "getGlobalStats"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint] & {
        totalPaymentCount: bigint;
        totalPaymentVolume: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPayerPayments"
  ): TypedContractMethod<[payer: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getPayment"
  ): TypedContractMethod<
    [paymentId: BytesLike],
    [PaymentRegistry.PaymentStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPaymentIdByTxHash"
  ): TypedContractMethod<[txHash: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "isTransactionRecorded"
  ): TypedContractMethod<[txHash: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "payerPayments"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "payments"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        bigint,
        string,
        string,
        bigint,
        string,
        string,
        string,
        bigint,
        string,
        boolean,
        boolean
      ] & {
        agentId: bigint;
        payer: string;
        payee: string;
        amount: bigint;
        token: string;
        serviceDescription: string;
        taskId: string;
        timestamp: bigint;
        txHash: string;
        verified: boolean;
        refunded: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "recordPayment"
  ): TypedContractMethod<
    [
      agentId: BigNumberish,
      payee: AddressLike,
      amount: BigNumberish,
      token: AddressLike,
      serviceDescription: string,
      taskId: string,
      txHash: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalPayments"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalVolume"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "txHashToPaymentId"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "verifyPayment"
  ): TypedContractMethod<[paymentId: BytesLike], [void], "nonpayable">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PaymentRecorded"
  ): TypedContractEvent<
    PaymentRecordedEvent.InputTuple,
    PaymentRecordedEvent.OutputTuple,
    PaymentRecordedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentRefunded"
  ): TypedContractEvent<
    PaymentRefundedEvent.InputTuple,
    PaymentRefundedEvent.OutputTuple,
    PaymentRefundedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentVerified"
  ): TypedContractEvent<
    PaymentVerifiedEvent.InputTuple,
    PaymentVerifiedEvent.OutputTuple,
    PaymentVerifiedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PaymentRecorded(bytes32,uint256,address,uint256,bytes32)": TypedContractEvent<
      PaymentRecordedEvent.InputTuple,
      PaymentRecordedEvent.OutputTuple,
      PaymentRecordedEvent.OutputObject
    >;
    PaymentRecorded: TypedContractEvent<
      PaymentRecordedEvent.InputTuple,
      PaymentRecordedEvent.OutputTuple,
      PaymentRecordedEvent.OutputObject
    >;

    "PaymentRefunded(bytes32,uint256,uint256)": TypedContractEvent<
      PaymentRefundedEvent.InputTuple,
      PaymentRefundedEvent.OutputTuple,
      PaymentRefundedEvent.OutputObject
    >;
    PaymentRefunded: TypedContractEvent<
      PaymentRefundedEvent.InputTuple,
      PaymentRefundedEvent.OutputTuple,
      PaymentRefundedEvent.OutputObject
    >;

    "PaymentVerified(bytes32,uint256)": TypedContractEvent<
      PaymentVerifiedEvent.InputTuple,
      PaymentVerifiedEvent.OutputTuple,
      PaymentVerifiedEvent.OutputObject
    >;
    PaymentVerified: TypedContractEvent<
      PaymentVerifiedEvent.InputTuple,
      PaymentVerifiedEvent.OutputTuple,
      PaymentVerifiedEvent.OutputObject
    >;
  };
}
