/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace ValidationRegistry {
  export type ValidationStruct = {
    agentId: BigNumberish;
    validationType: BigNumberish;
    validator: AddressLike;
    passed: boolean;
    resultHash: string;
    timestamp: BigNumberish;
    expiresAt: BigNumberish;
    metadata: string;
  };

  export type ValidationStructOutput = [
    agentId: bigint,
    validationType: bigint,
    validator: string,
    passed: boolean,
    resultHash: string,
    timestamp: bigint,
    expiresAt: bigint,
    metadata: string
  ] & {
    agentId: bigint;
    validationType: bigint;
    validator: string;
    passed: boolean;
    resultHash: string;
    timestamp: bigint;
    expiresAt: bigint;
    metadata: string;
  };

  export type ValidationStatsStruct = {
    totalValidations: BigNumberish;
    passedValidations: BigNumberish;
    failedValidations: BigNumberish;
    lastValidationTime: BigNumberish;
  };

  export type ValidationStatsStructOutput = [
    totalValidations: bigint,
    passedValidations: bigint,
    failedValidations: bigint,
    lastValidationTime: bigint
  ] & {
    totalValidations: bigint;
    passedValidations: bigint;
    failedValidations: bigint;
    lastValidationTime: bigint;
  };
}

export interface ValidationRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "VALIDATOR_ROLE"
      | "agentValidationStats"
      | "agentValidations"
      | "authorizeValidator"
      | "authorizedValidators"
      | "disputeValidation"
      | "disputedValidations"
      | "getActiveValidations"
      | "getRoleAdmin"
      | "getValidationScore"
      | "getValidationStats"
      | "getValidations"
      | "getValidationsByType"
      | "grantRole"
      | "hasActiveValidation"
      | "hasRole"
      | "renounceRole"
      | "resolveDispute"
      | "revokeRole"
      | "revokeValidator"
      | "submitValidation"
      | "supportsInterface"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DisputeResolved"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "ValidationDisputed"
      | "ValidationSubmitted"
      | "ValidatorAuthorized"
      | "ValidatorRevoked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VALIDATOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "agentValidationStats",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "agentValidations",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizeValidator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedValidators",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "disputeValidation",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "disputedValidations",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveValidations",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getValidationScore",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getValidationStats",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getValidations",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getValidationsByType",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasActiveValidation",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "resolveDispute",
    values: [BytesLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeValidator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitValidation",
    values: [BigNumberish, BigNumberish, boolean, string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VALIDATOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "agentValidationStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "agentValidations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizeValidator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedValidators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disputeValidation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disputedValidations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveValidations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getValidationScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getValidationStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getValidations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getValidationsByType",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasActiveValidation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "revokeValidator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitValidation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
}

export namespace DisputeResolvedEvent {
  export type InputTuple = [validationId: BytesLike, outcome: boolean];
  export type OutputTuple = [validationId: string, outcome: boolean];
  export interface OutputObject {
    validationId: string;
    outcome: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValidationDisputedEvent {
  export type InputTuple = [validationId: BytesLike, agentId: BigNumberish];
  export type OutputTuple = [validationId: string, agentId: bigint];
  export interface OutputObject {
    validationId: string;
    agentId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValidationSubmittedEvent {
  export type InputTuple = [
    agentId: BigNumberish,
    validationType: BigNumberish,
    validator: AddressLike,
    passed: boolean,
    resultHash: string
  ];
  export type OutputTuple = [
    agentId: bigint,
    validationType: bigint,
    validator: string,
    passed: boolean,
    resultHash: string
  ];
  export interface OutputObject {
    agentId: bigint;
    validationType: bigint;
    validator: string;
    passed: boolean;
    resultHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValidatorAuthorizedEvent {
  export type InputTuple = [validator: AddressLike];
  export type OutputTuple = [validator: string];
  export interface OutputObject {
    validator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValidatorRevokedEvent {
  export type InputTuple = [validator: AddressLike];
  export type OutputTuple = [validator: string];
  export interface OutputObject {
    validator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ValidationRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ValidationRegistry;
  waitForDeployment(): Promise<this>;

  interface: ValidationRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  VALIDATOR_ROLE: TypedContractMethod<[], [string], "view">;

  agentValidationStats: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint] & {
        totalValidations: bigint;
        passedValidations: bigint;
        failedValidations: bigint;
        lastValidationTime: bigint;
      }
    ],
    "view"
  >;

  agentValidations: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [bigint, bigint, string, boolean, string, bigint, bigint, string] & {
        agentId: bigint;
        validationType: bigint;
        validator: string;
        passed: boolean;
        resultHash: string;
        timestamp: bigint;
        expiresAt: bigint;
        metadata: string;
      }
    ],
    "view"
  >;

  authorizeValidator: TypedContractMethod<
    [validator: AddressLike],
    [void],
    "nonpayable"
  >;

  authorizedValidators: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  disputeValidation: TypedContractMethod<
    [agentId: BigNumberish, validationIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  disputedValidations: TypedContractMethod<
    [arg0: BytesLike],
    [boolean],
    "view"
  >;

  getActiveValidations: TypedContractMethod<
    [agentId: BigNumberish],
    [ValidationRegistry.ValidationStructOutput[]],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getValidationScore: TypedContractMethod<
    [agentId: BigNumberish],
    [bigint],
    "view"
  >;

  getValidationStats: TypedContractMethod<
    [agentId: BigNumberish],
    [ValidationRegistry.ValidationStatsStructOutput],
    "view"
  >;

  getValidations: TypedContractMethod<
    [agentId: BigNumberish],
    [ValidationRegistry.ValidationStructOutput[]],
    "view"
  >;

  getValidationsByType: TypedContractMethod<
    [agentId: BigNumberish, validationType: BigNumberish],
    [ValidationRegistry.ValidationStructOutput[]],
    "view"
  >;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasActiveValidation: TypedContractMethod<
    [agentId: BigNumberish, validationType: BigNumberish],
    [boolean],
    "view"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  resolveDispute: TypedContractMethod<
    [validationId: BytesLike, outcome: boolean],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeValidator: TypedContractMethod<
    [validator: AddressLike],
    [void],
    "nonpayable"
  >;

  submitValidation: TypedContractMethod<
    [
      agentId: BigNumberish,
      validationType: BigNumberish,
      passed: boolean,
      resultHash: string,
      expiresAt: BigNumberish,
      metadata: string
    ],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "VALIDATOR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "agentValidationStats"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint] & {
        totalValidations: bigint;
        passedValidations: bigint;
        failedValidations: bigint;
        lastValidationTime: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "agentValidations"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [bigint, bigint, string, boolean, string, bigint, bigint, string] & {
        agentId: bigint;
        validationType: bigint;
        validator: string;
        passed: boolean;
        resultHash: string;
        timestamp: bigint;
        expiresAt: bigint;
        metadata: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "authorizeValidator"
  ): TypedContractMethod<[validator: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "authorizedValidators"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "disputeValidation"
  ): TypedContractMethod<
    [agentId: BigNumberish, validationIndex: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "disputedValidations"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "getActiveValidations"
  ): TypedContractMethod<
    [agentId: BigNumberish],
    [ValidationRegistry.ValidationStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getValidationScore"
  ): TypedContractMethod<[agentId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getValidationStats"
  ): TypedContractMethod<
    [agentId: BigNumberish],
    [ValidationRegistry.ValidationStatsStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getValidations"
  ): TypedContractMethod<
    [agentId: BigNumberish],
    [ValidationRegistry.ValidationStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getValidationsByType"
  ): TypedContractMethod<
    [agentId: BigNumberish, validationType: BigNumberish],
    [ValidationRegistry.ValidationStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasActiveValidation"
  ): TypedContractMethod<
    [agentId: BigNumberish, validationType: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "resolveDispute"
  ): TypedContractMethod<
    [validationId: BytesLike, outcome: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeValidator"
  ): TypedContractMethod<[validator: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitValidation"
  ): TypedContractMethod<
    [
      agentId: BigNumberish,
      validationType: BigNumberish,
      passed: boolean,
      resultHash: string,
      expiresAt: BigNumberish,
      metadata: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;

  getEvent(
    key: "DisputeResolved"
  ): TypedContractEvent<
    DisputeResolvedEvent.InputTuple,
    DisputeResolvedEvent.OutputTuple,
    DisputeResolvedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "ValidationDisputed"
  ): TypedContractEvent<
    ValidationDisputedEvent.InputTuple,
    ValidationDisputedEvent.OutputTuple,
    ValidationDisputedEvent.OutputObject
  >;
  getEvent(
    key: "ValidationSubmitted"
  ): TypedContractEvent<
    ValidationSubmittedEvent.InputTuple,
    ValidationSubmittedEvent.OutputTuple,
    ValidationSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "ValidatorAuthorized"
  ): TypedContractEvent<
    ValidatorAuthorizedEvent.InputTuple,
    ValidatorAuthorizedEvent.OutputTuple,
    ValidatorAuthorizedEvent.OutputObject
  >;
  getEvent(
    key: "ValidatorRevoked"
  ): TypedContractEvent<
    ValidatorRevokedEvent.InputTuple,
    ValidatorRevokedEvent.OutputTuple,
    ValidatorRevokedEvent.OutputObject
  >;

  filters: {
    "DisputeResolved(bytes32,bool)": TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;
    DisputeResolved: TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "ValidationDisputed(bytes32,uint256)": TypedContractEvent<
      ValidationDisputedEvent.InputTuple,
      ValidationDisputedEvent.OutputTuple,
      ValidationDisputedEvent.OutputObject
    >;
    ValidationDisputed: TypedContractEvent<
      ValidationDisputedEvent.InputTuple,
      ValidationDisputedEvent.OutputTuple,
      ValidationDisputedEvent.OutputObject
    >;

    "ValidationSubmitted(uint256,uint8,address,bool,string)": TypedContractEvent<
      ValidationSubmittedEvent.InputTuple,
      ValidationSubmittedEvent.OutputTuple,
      ValidationSubmittedEvent.OutputObject
    >;
    ValidationSubmitted: TypedContractEvent<
      ValidationSubmittedEvent.InputTuple,
      ValidationSubmittedEvent.OutputTuple,
      ValidationSubmittedEvent.OutputObject
    >;

    "ValidatorAuthorized(address)": TypedContractEvent<
      ValidatorAuthorizedEvent.InputTuple,
      ValidatorAuthorizedEvent.OutputTuple,
      ValidatorAuthorizedEvent.OutputObject
    >;
    ValidatorAuthorized: TypedContractEvent<
      ValidatorAuthorizedEvent.InputTuple,
      ValidatorAuthorizedEvent.OutputTuple,
      ValidatorAuthorizedEvent.OutputObject
    >;

    "ValidatorRevoked(address)": TypedContractEvent<
      ValidatorRevokedEvent.InputTuple,
      ValidatorRevokedEvent.OutputTuple,
      ValidatorRevokedEvent.OutputObject
    >;
    ValidatorRevoked: TypedContractEvent<
      ValidatorRevokedEvent.InputTuple,
      ValidatorRevokedEvent.OutputTuple,
      ValidatorRevokedEvent.OutputObject
    >;
  };
}
