/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IPaymentRegistry__factory } from "./IPaymentRegistry__factory";
export { ReputationRegistry__factory } from "./ReputationRegistry__factory";
