/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPaymentRegistry,
  IPaymentRegistryInterface,
} from "../../../contracts/ReputationRegistry.sol/IPaymentRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "paymentId",
        type: "bytes32",
      },
    ],
    name: "getPayment",
    outputs: [
      {
        internalType: "uint256",
        name: "agentId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "payer",
        type: "address",
      },
      {
        internalType: "address",
        name: "payee",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "string",
        name: "serviceDescription",
        type: "string",
      },
      {
        internalType: "string",
        name: "taskId",
        type: "string",
      },
      {
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
      {
        internalType: "bytes32",
        name: "txHash",
        type: "bytes32",
      },
      {
        internalType: "bool",
        name: "verified",
        type: "bool",
      },
      {
        internalType: "bool",
        name: "refunded",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "txHash",
        type: "bytes32",
      },
    ],
    name: "isTransactionRecorded",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IPaymentRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IPaymentRegistryInterface {
    return new Interface(_abi) as IPaymentRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPaymentRegistry {
    return new Contract(address, _abi, runner) as unknown as IPaymentRegistry;
  }
}
