/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AgentIdentityRegistry__factory } from "./AgentIdentityRegistry__factory";
export { ReputationRegistry__factory } from "./ReputationRegistry__factory";
export { ValidationRegistry__factory } from "./ValidationRegistry__factory";
